### ISSUE TITLE
Doesn't compile when editing from another dir

### ISSUE THREAD

**Issue by gvolk0** [Olical/nfnl#11]
```
cd test
nvim fnl/t.fnl # no fnl/t.lua
cd fnl/ && nvim t.fnl # -> t.lua
```

test/.nfnl.fnl:
```
{
  :source-file-patterns ["*.fnl" "**/*.fnl"]
}
```

This is particularly bothersome given that most people are navigating to files using fzf or tree view  which don't change the cwd.

Am I missing something simple?

**Comment by Olical** [comment]
Oh interesting, I think I have some core assumptions where the `.nfnl.fnl` file is found by walking up from your CWD. I'll see how easy it'd be to base everything off of the current file path instead. The only danger here is that users configuring their own `:fnl-path->lua-path` function will need to potentially deal with times when the editor isn't in the expected CWD.

Just in case their logic depends on it, like in my example code from the [readme](https://github.com/Olical/nfnl#writing-lua-elsewhere).

```fennel
(local config (require :nfnl.config))
(local default (config.default))

{:fnl-path->lua-path (fn [fnl-path]
                       (let [rel-fnl-path (vim.fn.fnamemodify fnl-path ":.")]
                         (default.fnl-path->lua-path (.. "some-other-dir/" rel-fnl-path))))}
```

**Comment by gvolk0** [comment]
Yea don't think there's a way around it if you want a custom output path.

Also just found this (seems kinda related) - there's a bug in the generated lua code comment depending on whether I do `nvim util.fnl` or `nvim #then nav to util.fnl`

diff:
```
--- [nfnl] Compiled from util.fnl by https://github.com/Olical/nfnl, do not edit.
+-- [nfnl] Compiled from  by https://github.com/Olical/nfnl, do not edit.
 local function dump(o)
```

What's odd is that the filename is missing when doing `nvim util.fnl` rather than when navigating from within vim which I thought might be the problem.

**Comment by Olical** [comment]
Could you try this again now? I may have accidentally found and fixed the bug which was to do with autocmd events sometimes including relative paths for the affected file and sometimes being absolute?

This seems to be something that depends on Neovim configuration because my test suite ran locally but failed in CI in the same way you described (blank file after "Compiled from"). This now has a e2e test in CI that checks this sort of thing automatically on push, so it shouldn't happen again. If this _was_ the issue.

I just tried editing a fnl file from a directory above and beside another one and both compiled as expected wile the CWD was set wrong.

So I wrote nfnl to work like this all along, I just forgot and there was a bug that was breaking it in a weird way.

**Comment by gvolk0** [comment]
Yep, confirmed fix on both bugs - thanks!
