### ISSUE TITLE
Non-deterministic output of lua?

### ISSUE THREAD

**Issue by stefanvanburen** [Olical/nfnl#13]
Hi hi, great project - moved over from aniseed and it's been great so far!

I did notice one thing with checking in the generated files, though, is that occasionally the fields in lua will be reordered, leading to diffs in the generated code where there probably shouldn't be.

For example, the fennel code here:

https://github.com/stefanvanburen/dotfiles/blob/a8cabd4ca54e2052b71b88acb09f00f5f05f27e8/.config/nvim/init.fnl#L517-L538

Seems to occasionally be regenerated with a different field order, resulting in a diff:

```diff
-lspconfig.gopls.setup({cmd = {"gopls", "-remote=auto"}, settings = {gopls = {staticcheck = true, analyses = {unusedparams = true, unusedwrite = true, nilness = true}, hints = {parameterNames = true, functionTypeParameters = false, rangeVariableTypes = false, compositeLiteralFields = false, compositeLiteralTypes = false, assignVariableTypes = false, constantValues = false}}}})
+lspconfig.gopls.setup({cmd = {"gopls", "-remote=auto"}, settings = {gopls = {staticcheck = true, analyses = {unusedparams = true, unusedwrite = true, nilness = true}, hints = {parameterNames = true, assignVariableTypes = false, constantValues = false, functionTypeParameters = false, rangeVariableTypes = false, compositeLiteralFields = false, compositeLiteralTypes = false}}}})
```

(Particularly that last table, where it seems like the `true` field always comes first, but the `false` fields are ... in random order, as far as I can tell?)

Not sure if this is something that can be fixed or worked around, happy to help debug further!

**Comment by Olical** [comment]
So as far as I know this is a Fennel compiler thing, I've seen this in Aniseed too but more frequently since all files get recompiled rather than the one you're editing.

I'm not sure if there's any compiler flags I can set to make this stable, it might be something we should reproduce with the Fennel compiler on the CLI and then report upstream.

I'm away until late Sunday otherwise I'd take a look, but I should be able to investigate more when I'm home.

If you can find a compiler flag, open issue or just reproduce it without nfnl and report it, that'd be amazing. I'll get to it soon after I'm home otherwise.

**Comment by stefanvanburen** [comment]
Thanks - no rush at all. Doing a bit of digging, it doesn't look like there's a compiler option for it: https://fennel-lang.org/api. There are [a few issues relating to unstable output in the GitHub repo, but all are closed, currently](https://github.com/bakpakin/Fennel/issues?q=unstable). May have a chance to try to reproduce this weekend.

**Comment by Olical** [comment]
What's odd is that I can't reproduce this at the CLI with luajit (which is what Neovim runs Fennel under).

```fish
# Fish shell

for n in (seq 1 100)
  luajit fennel-1.3.1 --compile foo.fnl > lua/$n.lua
end

md5sum lua/*

# They're all the same!
```

I ran this a few times and it seems fine. I tried the minimal Fennel that you were seeing move around and I tried the whole file. Maybe the Fennel CLI does something fancy to keep things stable that the Lua API doesn't do by default, but I find that hard to believe.

**Comment by Olical** [comment]
And I can't reproduce this with nfnl with your file, I set up a macro to write the file 100 times and had `entr` print the `md5sum` of each Lua file, it was the same every time. How weird! Everything seems great... you don't have some other thing maybe compiling this file do you? Or like Neovim versions changing between compiles? Because maybe LuaJIT got updated or something between Neovim versions and that changed the sort order?

**Comment by stefanvanburen** [comment]
oo - that could maybe be it. I did downgrade from 0.10-HEAD to 0.9 for stability reasons, so could explain the change in output. (Really did not think that would be related!).

Since you're unable to repro and there's a fairly decent chance that the change in versions resulted in the non-deterministic output, I'll close this for now.
