### ISSUE TITLE
Any way to disable compile on save?

### ISSUE THREAD

**Issue by csy19960309** [Olical/nfnl#17]
It seems that compile on save conflicts with my format on save so I wish to trigger compiling manually. How do I set up the configuration to achieve that?

**Comment by Olical** [comment]
Oh interesting, kinda against the ethos of the plugin but I think it can be supported fairly easily. Not possible just yet, but I'll add it for you.

What conflict are you seeing? An error every time you write a file? Would love some more context here because maybe both can be supported easily.

**Comment by Olical** [comment]
Hmm, do you think this config should be project by project (i.e. you set something in your `.nfnl.fnl` file for the project) orrr should it be an argument passed to `require("nfnl").setup({...})` that works globally. I'm leaning towards global setup call since that integrates nicely with things like lazy.nvim, but I'm not sure.

Maybe it should just be a `g:nfnl#compile_on_write` variable like the good old days 😅

**Comment by Olical** [comment]
Alongside what error you're running into, I'd also like to know which formatter you're using / how. Like are you formatting the fennel on save? Or the Lua file? I guess the fennel and I'm interested into how that's hooked up and how that could possibly cause an issue with this other autocmd, it's pretty unobtrusive 🤔

**Comment by csy19960309** [comment]
> 

Thank you for your interest in my issue and I am sorry for my late reply! I am using a plugin _elentok/format-on-save.nvim_ to format my fennel code with the formatter _fnlfmt_. I find that problems occur when there are compiling errors. When I save my code,  all my later modifications are wiped if I make errors after my last saving. So a possible solution is preventing formatting if there is any compiling error. As I am learning towards lua programming, it may take me some time to adjust my config to meet my needs. Furthermore I will take some time to study your suggestions.

**Comment by Olical** [comment]
Have you tried repeating this without nfnl enabled? So saving a Fennel file with no nfnl but with fnlfmt? I'd like to isolate this to check if it's just the formatter behaving strangely and not nfnl. I personally can't see how nfnl could cause this behaviour since all it does is:

 * Read the buffer content.
 * Compile to Lua in memory.
 * Print errors if there are using the `notify` system (which ends up in `:messages` / notify popups if you have a plugin to display them like that https://github.com/rcarriga/nvim-notify)
 * Write the resulting Lua to the appropriate Lua file if it compiled okay.

nfnl does not ever touch your Fennel buffer or trigger actual Lua errors that would interrupt any other Neovim processes. It's essentially just echoing / printing errors. So no other plugins or systems should be affected.

I _suspect_ the issue lies with the formatting alone and not nfnl, so I'd like to rule that out. I could be wrong and you could've already checked this of course, I'm sorry if so. Just need to be thorough because I'd like to avoid adding options unless I absolutely need to.

Once the floodgate of configuration opens, it only gets more complex and difficult to manage + document. So the less options and the more "It Just Works" the better in my opinion.

**Comment by csy19960309** [comment]
> Have you tried repeating this without nfnl enabled? So saving a Fennel file with no nfnl but with fnlfmt? I'd like to isolate this to check if it's just the formatter behaving strangely and not nfnl. I personally can't see how nfnl could cause this behaviour since all it does is:
> 
> * Read the buffer content.
> * Compile to Lua in memory.
> * Print errors if there are using the `notify` system (which ends up in `:messages` / notify popups if you have a plugin to display them like that https://github.com/rcarriga/nvim-notify)
> * Write the resulting Lua to the appropriate Lua file if it compiled okay.
> 
> nfnl does not ever touch your Fennel buffer or trigger actual Lua errors that would interrupt any other Neovim processes. It's essentially just echoing / printing errors. So no other plugins or systems should be affected.
> 
> I _suspect_ the issue lies with the formatting alone and not nfnl, so I'd like to rule that out. I could be wrong and you could've already checked this of course, I'm sorry if so. Just need to be thorough because I'd like to avoid adding options unless I absolutely need to.
> 
> Once the floodgate of configuration opens, it only gets more complex and difficult to manage + document. So the less options and the more "It Just Works" the better in my opinion.

Thanks for the suggestions and it is found you are right -- the buffer content is rolled back because formatting fails. As I am able to undo the rolling back with _U_, the only unresolved problem is under the circumstance where I make compiling errors, nfnl does not print out what compiling errors are. Do you have any idea about that?

**Comment by Olical** [comment]
Hm, nfnl should be showing you compilation errors already, it does for me. Have you checked your `:messages`? It notifies you with the `vim.notify` system (`:h vim.notify`) which will go into your `:messages` if you don't have a UI for it installed.

**Comment by Olical** [comment]
It may well be sending it to messages but the window at the bottom is getting cleared by the formatter or some other plugin before you get to read it 🤔

**Comment by csy19960309** [comment]
> Hm, nfnl should be showing you compilation errors already, it does for me. Have you checked your `:messages`? It notifies you with the `vim.notify` system (`:h vim.notify`) which will go into your `:messages` if you don't have a UI for it installed.

`:messages` doesn't show me the compiling errors. I guess they are cleared by the formatting plugin indeed. As it turns out to be an issue of another plugin, should I close this issue?

**Comment by Olical** [comment]
Oh no, that's weird! So if you have the formatter disabled do the errors show up on file write? Would be good to rule that out.

**Comment by Olical** [comment]
Going to close this issue but please do re-open if you're still using this, having issues and think it's something I could help fix. Hope things are going well for you!

**Comment by csy19960309** [comment]
Thanks for caring about this issue. As a tip for those who face the same issue, I finally solved it by switch my formatting plugin to [https://github.com/stevearc/conform.nvim](url). In this way I can compile and format my code with a single save.
