### ISSUE TITLE
Latest main doesn't compile on windows

### ISSUE THREAD

**Issue by Kethku** [Olical/nfnl#36]
Running `:NfnlCompileAllFiles` gives this:
![image](https://github.com/Olical/nfnl/assets/3323631/f0421f6e-fa5f-4796-80f9-e659e52caf1b)

I'm not sure whats going on here, but no matter what I set source-file-patterns to, I can't seem to get nfnl to compile anything.

Any hints how to debug this further?

**Comment by Kethku** [comment]
The double backslash stood out to me. So I manually changed the backslash in fs.lua to a forward slash (obviously this would get changed in a more reasonable way in the future) and things are working normally again. All of the files get compiled as expected.

Was the double backslash returned at some point from nvim filesystem apis and the file separator selected to address that at some point in the past?

**Comment by Kethku** [comment]
Mmmm or at least making that change fixed the manual compilation via `NfnlCompileAllFiles` but it seems like the autocmd is not running properly. At the very least that issue is a clue

**Comment by Kethku** [comment]
I reverted to https://github.com/Olical/nfnl/commit/9c54c2cfd4a3e3eac43473c6fe8fcfb15874e6c4 and things are working as expected

**Comment by Olical** [comment]
Hey! Sorry I was away last week! Sorry about the issue but thanks for giving this context, that `\` is coming from inside nfnl since we use OS local path separators in all paths, or at least we should...

So in the `nfnl.fs` module there's a `path-sep` function that returns a forward or backslash depending on the OS. We use that in a few places but also in the split and join path functions.

I suspect a Neovim API is returning a forward slash path somewhere and I'm mixing it with a backslash path. And maybe with all of the APIs I'm using I just need to use forward slashes in Windows? Although that feels like a dangerous assumption.

I wonder why some of your paths have forward and some have backward. I definitely needed to use the right separators in Aniseed / Conjure which is why this logic is here at all, it was to support Windows. I just wonder if the APIs I'm using now don't need that conversion.

I'll look into this, just wanted to ack it first.

**Comment by UnderCooled** [comment]
I was using the nightly build three days ago, autocmd failed to work like #32, than I updated the nightly build again two days ago, autocmd works fine.

**Comment by UnderCooled** [comment]
I tested `NfnlCompileAllFiles`, it works fine.

![image](https://github.com/Olical/nfnl/assets/161503/759ac633-5e17-4963-95fa-187c237d29cf)

```
NVIM v0.10.0-dev-2539+ga69c72063
Build type: RelWithDebInfo
LuaJIT 2.1.1707061634

nfnl @ 92f03c0
```

Here's my .nfnl.fnl:
```fennel
{:source-file-patterns ["fnl/**/*.fnl" "fnl/*.fnl" "*.fnl"]
 :compiler-options {:compilerEnv _G}}
```

**Comment by Kethku** [comment]
I updated to the newest nvim nightly and am getting very strange results.
NfnlCompileAllFiles continues to give the issue I see above.
Weirdly the autocommand seems to compile *once*. So the first change I make and save in a fennel file will get compiled but after that no further compilation happens.

I'd be happy to debug some of this further myself, but I'm sorta at a loss for where to start.

**Comment by UnderCooled** [comment]
> I updated to the newest nvim nightly and am getting very strange results. NfnlCompileAllFiles continues to give the issue I see above. Weirdly the autocommand seems to compile _once_. So the first change I make and save in a fennel file will get compiled but after that no further compilation happens.
> 
> I'd be happy to debug some of this further myself, but I'm sorta at a loss for where to start.

You can use `:autocmd BufWritePost` to check nfnl's autocmds bound to the right buffer ID like in #32.

My output of `:echo fnamemodify(stdpath('config'), ':p')` is `C:\Users\unco\AppData\Local\nvim` without forward slashes.
You can check it with `:verbose set shellslash?`.

**Comment by Olical** [comment]
Sorry about the delay! Had a lot on recently. So the autocmd thing is SUPER weird and should never happen, that's not how autocmds work, they exist until cleared. So something else must be at play here... I'll need to investigate.

What I'm seeing here is that despite being on Windows, almost all of your paths are `/` based, not `\` based... which is not how I thought Windows paths worked which is why nfnl tries to respect your OS paths.

The paths in the original issue report show `/` for almost all segments then a `\` for the one segment where nfnl has joined two paths together and selected a path separator based on your OS.

So do ALL paths you see in Neovim use forward slashes like Unix? I know I absolutely needed to do this smart slash selection in Conjure when interacting with the filesystem, so why is that not required in this case? Is it maybe a Windows setting or a Neovim one?

I'm worried if I just remove the smart slash selection it'll fix your issue and break some other Windows user's experience 🤔

**Comment by Olical** [comment]
And if you look at @UnderCooled's screenshot, they're all backslashes! So @Kethku, are you under WSL or something? Or even some sort of bash / unix-y environment under windows when @UnderCooled is under pure Windows with no Unix-y layers?

I don't know the Windows developer landscape so I think I need some more context and guidance here wrt Windows paths and how they can vary. I want to help, just need some more info. I'll see if I can work out what's going on with that autocmd too, that should never happen.

**Comment by Olical** [comment]
It's also worth noting that things like `source-file-patterns` need to match the path separator your OS uses because it needs to match the file paths that Neovim reports to nfnl. The default nfnl provides for you will use your OS path separator, so if you override the default, make sure you use your OS local path style.

The default value is built from `["*.fnl" (fs.join-path ["**" "*.fnl"])]`, so you could use `fs.join-path` as well to get the same automatic behaviour if you need portable config that works on Windows and Linux.

**Comment by Olical** [comment]
Oh, @Kethku, do you have `vim.opt.shellslash` set?

**Comment by Olical** [comment]
Okay, if you DO use it (it explains the `/` on Windows!) then nfnl should support it now. I hope. I still don't know what's going on with the autocmds though, those work just fine for me, maybe another windows thing?

**Comment by Kethku** [comment]
I'm so sorry I just realized you responded. I missed the notification.

> So do ALL paths you see in Neovim use forward slashes like Unix?

Hitting `1<c-g>` prints with backslashes.
Executing `:lua print(vim.fn.getcwd())` prints with forward slashes.

> So @Kethku, are you under WSL or something?

Nope! I'm running windows 11. No wsl and no configuration that I can think of that would cause this.

> Oh, @Kethku, do you have vim.opt.shellslash set?

Ok weirdly this is being set by some plugin in my config. Very frustrating because I assumed it wasn't since I don't set it myself. Regardless though I pulled the latest version and it looks like that fixed the path issue!

However I'm still getting the autocmd only running once. Shall I create a new issue for that?

**Comment by Kethku** [comment]
I am updated to current main though which means the fix for shellslash seems to not have worked. This isn't an issue for me now that I've removed the shellslash option, but its probably worth tracking down

**Comment by Kamholtz** [comment]
I have uploaded a repro config here: https://github.com/Kamholtz/nfnl-aucommand-bug-repro/tree/main

The README.md shows the steps taken to reproduce the issue on a recent nightly build, and compares it to the working behaviour on the latest stable build.

**Comment by Olical** [comment]
Incredible reporting! Thank you so much! So this is two issues really, one was that I didn't take `shellslash` into account and the other is that on Nightly the autocommand vanishes after it executes. That to me sounds like a Nightly Neovim bug and not something I should work around because that's just not how autocommands work. I'm going to have a poke through the Neovim repo, if this is happening to many autocmds this should be a huge deal there in the issues.

At least we have one issue fixed and I understand Windows + Neovim path shenanigans a little better than I did before. I'm trying to abstract path stuff away so bugs like this won't happen again + other users of nfnl things get to lean on `nfnl.fs` which hopefully means all systems built on nfnl can benefit from these lessons.

**Comment by Olical** [comment]
I can reproduce the autocmd vanishing on nightly after one run! I see no issues open in the Neovim repo that seem relevant (although I may have missed it). Now to determine if all autocmds are broken, all BufWritePost are broken or if it's _just_ the nfnl one and then why. Maybe it's the name I'm giving it that Nightly doesn't like which is why others haven't run into this bug. And I do think it's a bug.

I checked if the default in the Lua API changed so `once=true` by default, but nope, it's the same!

**Comment by Olical** [comment]
FOUND IT. It's a Neovim bug. If a callback to an autocmd returns a Lua value like a table then the autocmd is removed, if I return `nil` it fixes the issue. I think I'll raise a Neovim bug I guess?

**Comment by Olical** [comment]
Pushed a fix to `main`.

**Comment by Olical** [comment]
https://github.com/neovim/neovim/issues/28127 issue here

**Comment by Olical** [comment]
So apparently that's a feature! Not sure when it was added, maybe it was always this way? But if an autocmd callback returns anything other than `nil` or `false` it will be deleted. News to me but now we know, I'll make sure none of my autocmd callbacks return something truthy, I do worry this will break Conjure in a bunch of places too and I need to go hunt through my callbacks now 😭 

Thanks for these in depth reports and I hope my change fixes things for you!

**Comment by Olical** [comment]
Ah, on like 126 of `:help news`

```
• Returning any truthy value from a callback passed to |nvim_create_autocmd()|
  (rather than just `true`) will delete the autocommand.
```

I would've struggled to find that myself and this should probably be marked as a breaking change in my opinion but ¯\\\_(ツ)\_/¯

**Comment by Olical** [comment]
I also think that API is unintuitive and smells like "boolean flag changing behaviour of functions", shame but I'll work around it from now on.

**Comment by Olical** [comment]
I've realised why this isn't a big deal for most people! In Fennel we have implicit returns, in Lua it's nil by default! So all pure Lua code gets nil unless they explicitly return something, Fennel code always returns the last thing so we have to opt OUT.

So, for Fennel users, be careful about what your autocmd callbacks return.

**Comment by Kamholtz** [comment]
Wow, that's a real gotcha for fennel users. I have confirmed that the latest `main` has resolved the problem for me. Thank you!

**Comment by Kethku** [comment]
Amazing. Thanks so much for the in depth investigation <3
